## Functions to create a special "matrix" and calculate the inverse of 
## that special matrix.  The functions store the data globally so that 
## calculations do not need to be done repeatedly.

## makeCacheMatrix stores the provided matrix globally and returns a list of
## functions to access the data and save the inverse.  The input is
## assumed to be an invertible matrix.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setSolve <- function(invX) inv<<- invX
  getSolve <- function() inv
  list(set = set, get = get,
       setSolve = setSolve,
       getSolve = getSolve)

}


## cacheSolve takes a special "matrix" (list) generated by makeCacheMatrix
## If the inverse has already been calculated, it returns the cached inverse,
## otherwise, it calculates the inverse,stores it and returns it.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  invX <- x$getSolve()
  if(!is.null(invX)) {
    message("getting cached data")
    return(invX)
  }
  data <- x$get()
  inv <- solve(data, ...)
  x$setSolve(inv)
  inv
}
